name: ur_hub_test_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  http: ^0.13.4
  get_it: ^7.2.0
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  badges: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
